version: '3'
services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb-shared
    hostname: dynamodb
    restart: always
    ports:
      - 8000:8000
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath .'
